In [78]:
import pandas as pd
import numpy as np

#make dataset
earthquake= pd.DataFrame({
    "PHI_E" : [0,0,0,0,40,40,40,60,60,60],
    "LAMBDA_E" : [0,0,0,-30,0,0,0,0,0,0],
    "PHI_S": [1,5,10,60,41,45,50,61,65,70],
    "LAMBDA_S": [1,5,10,60,1,5,10,1,5,10]

})

delX = np.array(111.195*(earthquake["PHI_S"] - earthquake["PHI_E"]))
delY = np.array(111.195*(earthquake["LAMBDA_S"] - earthquake["LAMBDA_E"])* 
                np.cos(np.radians((earthquake["PHI_E"] + earthquake["PHI_S"])/ 2)))


# distance, azimuth, back azimuth to be included as columns of the earthquake dataset
dist_km = np.sqrt(np.power(delX, 2) + np.power(delY, 2))
azimuth = np.degrees(np.arctan(delY/delX))
backAzimuth = np.degrees(np.arctan(delY/delX)) + 180

#assign new columns
earthquake['Dist(km)'] = dist_km
earthquake['Azim'] = azimuth
earthquake['backAzimuth'] = backAzimuth
earthquake

   PHI_E  LAMBDA_E  PHI_S  LAMBDA_S      Dist(km)       Azim  backAzimuth
0      0         0      1         1    157.250483  44.998909   224.998909
1      0         0      5         5    785.893298  44.972721   224.972721
2      0         0     10        10   1569.545638  44.890778   224.890778
3      0       -30     60        60  10937.315651  52.410911   232.410911
4     40         0     41         1    139.691072  37.249575   217.249575
5     40         0     45         5    690.747840  36.400510   216.400510
6     40         0     50        10   1361.855060  35.264390   215.264390
7     60         0     61         1    123.945319  26.216721   206.216721
8     60         0     65         5    612.383630  24.785066   204.785066
9     60         0     70        10   1207.173294  22.909807   202.909807

In [76]:
#Input epicenter and station coordinates and get the results

phi_e = int(input("Enter the epicenter latitude : "))
lambda_e = int(input("Enter the epicenter longitude : "))
phi_s = int(input("Enter the station latitude : "))
lambda_s = int(input("Enter the station longitude : "))

delX = 111.195 * (phi_s - phi_e)
delY = 111.195 * (lambda_s - lambda_e) * np.cos(np.radians((phi_e + phi_s) / 2))


dist_km = np.sqrt(np.power(delX, 2) + np.power(delY, 2))
Az = np.degrees(np.arctan(delY/delX))
Baz = np.degrees(np.arctan(delY/delX)) + 180

# Testing for the first row
print("Epicentral distance {:.2f} km".format(dist_km))
print("Azimuth = {:.2f} degree".format(Az))
print("Back azimuth = {:.2f} degree".format(Baz))

Enter the epicenter latitude : 0
Enter the epicenter longitude : 0
Enter the station latitude : 1
Enter the station longitude : 1
Epicentral distance 157.25 km
Azimuth = 45.00 degree
Back azimuth = 225.00 degree